# Generated by Django 3.0.5 on 2020-04-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prajwolmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailList',
            new_name='Email',
        ),
    ]
